### ISSUE TITLE
Project Review: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [ChuckleWacker/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4/4
* _Comment(s):_ CSS file is appropriately linked to the HTML using a relative path 👍 
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4/4
* _Comment(s):_ Pretty much everything from the design specification has been included in the project. Styling looks perfect!
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4/4
* _Comment(s):_ All of the HTML elements are used appropriately and the structure/organization throughout `index.html` looks great.
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4/4
* _Comment(s):_ CSS syntax/selectors look good as well. I don't see any glaring issues here and you've kept the file concise, without repeating yourself.
 
### Overall Score: 16/16 🔥 
Awesome work!

**Comment by ChuckleWacker** [comment]
Thank you!! :-)
